### ISSUE TITLE
how to set bios?

### ISSUE THREAD

**Issue by jiyuefeng** [shuai132/ThinkPad-X13-EFI#1]

**Comment by shuai132** [comment]
https://apple.sqlsec.com/3-%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C/3-1.html

**Comment by shuai132** [comment]
https://dortania.github.io/OpenCore-Install-Guide/prerequisites.html

**Comment by jiyuefeng** [comment]
可以加你QQ么？

**Comment by shuai132** [comment]
可以  邮箱就是~
